version: '3'

services:
  faucet-server:
    container_name: faucet-server
    build: ./
    command: ["/bin/bash", "-c", "/faucet/start.sh"]
    ports:
      - "3000:3000"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - faucet-pg

  faucet-pg:
    image: postgres:alpine
    container_name: faucet-pg
    ports:
      - 25432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: faucet
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
